print ("--------------------------------------------------")
frase = input("Dame una frase: ")
frase1 = frase.lower()
a = frase1.count("a")
e = frase1.count("e")
i = frase1.count("i")
o = frase1.count("o")
u = frase1.count("u")
totalvoc = a + e + i + o + u
print ("Total de vocales: ", totalvoc)
print ("--------------------------------------------------")
print ("Hay vocales a:", a)
print ("Hay vocales e:", e)
print ("Hay vocales i:", i)
print ("Hay vocales o:", o)
print ("Hay vocales u:", u)
print ("--------------------------------------------------")
frase = frase.replace("a","")
frase = frase.replace("A","")
frase = frase.replace("e","")
frase = frase.replace("E","")
frase = frase.replace("i","")
frase = frase.replace("I","")
frase = frase.replace("o","")
frase = frase.replace("O","")
frase = frase.replace("u","")
frase = frase.replace("U","")
print (frase)
print ("--------------------------------------------------")