print ("--------------------------------------------------")
#nombres = (input("Dame el primer nombre: "), input("Dame el segundo nombre: "), input("Dame el tercer nombre: "))
nombres = ("Abner", "Adolfo", "Roberto")
#print ("Recibi: ", nombres)
print ("Estimado", nombres[0], "vote por mí.")
print ("Estimado", nombres[1], "vote por mí.")
print ("Estimado", nombres[2], "vote por mí.")
print ("--------------------------------------------------")
#genero = (input("Dame el primer genero: "), input("Dame el segundo genero: "), input("Dame el tercer genero: "))
genero = ("Masculino", "Masculino", "Masculino")
nomgen = (nombres, genero)
#nomgen = (nombres[0] + genero[0], nombres[1] + genero[1], nombres[2] + genero[2])
print (nomgen)
print ("--------------------------------------------------")